version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ee:13.9.5-ee.0
    container_name: cve-2021-22205
    restart: always
    hostname: 'gitlab.example.com'  # Can change to other hostname
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
