version: "3"

services:
  gitlab:
    build: gitlab/.
    cap_add:
      - NET_ADMIN
    container_name: cve-2021-22205
    environment:
      GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
    hostname: ${GITLAB_HOSTNAME}
    image: cve-2021-22205
    networks:
      - cve-2021-22205
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab

networks:
  cve-2021-22205:
    name: cve-2021-22205
